### ISSUE TITLE
AttributeError: module 'baselines.common.tf_util' has no attribute 'get_session'

### ISSUE THREAD

**Issue by itzmestar** [grauwolf32/openai-game#1]
hi, 
I am trying to run run_acktr.py on python 3.6 
but i get this error: 
>>> 
 RESTART: C:\Users\abc\Desktop\openai\work\openai-game\python\run_acktr.py 
[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.[0m
[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.[0m
[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.[0m
[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.[0m
Logging to C:\Users\abc\AppData\Local\Temp\openai-2018-02-21-23-53-22-432413
[33mWARN: Could not seed environment <GatheringGameEnv<1>>[0m
Use async eigen decomp
updating 12 eigenvalue/vectors
projecting 3 gradient matrices
Use async eigen decomp
updating 14 eigenvalue/vectors
projecting 4 gradient matrices
Traceback (most recent call last):
  File "C:\Users\abc\Desktop\openai\work\openai-game\python\run_acktr.py", line 62, in <module>
    train(num_timesteps=args.num_timesteps, seed=args.seed, env_name=args.env, fname=args.fname)
  File "C:\Users\abc\Desktop\openai\work\openai-game\python\run_acktr.py", line 44, in train
    num_timesteps=num_timesteps, animate=visualization, fname=fname)
  File "C:\Users\abc\Desktop\openai\work\openai-game\python\acktr_cont.py", line 82, in learn
    enqueue_threads.extend(qr.create_threads(U.get_session(), coord=coord, start=True))
AttributeError: module 'baselines.common.tf_util' has no attribute 'get_session'
>>> 

I have the latest openai/baselines code. 
I checked indeed 'baselines.common.tf_util' has make_session but no 'get_session'
should I replace acktr_cont.py with the file from baselines??

**Comment by grauwolf32** [comment]
Hello, 
In the old version of baselines i had this function:
def get_session():
    return tf.get_default_session()

I think, you can use tf.get_default_session() instead of U.get_session()
I add some code to acktr_cont.py which can save/load model from checkpoints. If you don't want to make checkpoints, you can use acktr_cont.py from baselines.

To run game simulation from checkpoint you can use ai_runner.py --fname ./model/gathering.ckpt 
Also i made little changes to baselines/acktr/policies.py, - in GaussianMlpPolicy i use tf.nn.elu activation function, rather than default tf.nn.tanh. (Not sure that gathering.ckpt  would work without this change)

**Comment by itzmestar** [comment]
thanks for the reply.

i got older version of baselines as well. running run_acktr.py with it gives another issue.

also i tried to run ai_runner.py which fails in module import:
Traceback (most recent call last):
  File "ai_runner.py", line 7, in <module>
    from micro_env import *
ModuleNotFoundError: No module named 'micro_env'

I couldn't find this micro_env in pip either.

**Comment by grauwolf32** [comment]
Check my latest commit,  It should be working now (I made an update for latest versions of gym and baselines)

**Comment by itzmestar** [comment]
its working. thanks 👍

**Comment by Joshwani** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.q1blue, @clemsos, @kidmam, @eazeye, @luisfidelis, @natzuu, @hsavit1, @atlaschiew, @enzg, @justinbosscher, @qiuchenghui, @the-neo-zeed, @Tanakpek, @adragomir, @KyleTang, @chentsulin, @thomasyuan, @toninorair, @cone26, @anthontaylor
